version: '3.2'
services:
  web:
    image: dgraziotin/nginx-webdav-nononsense
    container_name: file_server
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      CLIENT_MAX_BODY_SIZE: '999M'
      PUID: $UID
      PGID: $GID
    ports: 
      - 8889:80